### ISSUE TITLE
Should implement-an-exercise-from-specification.md#configuring-the-exercise include nextercism keys?

### ISSUE THREAD

**Issue by petertseng** [exercism/legacy-docs#92]
https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#configuring-the-exercise has slug, difficulty, topics. Should the example include all things in https://github.com/exercism/meta/issues/16 ? Should it instead incorporate https://github.com/exercism/meta/issues/16 by reference? Should something else happen?

If not, we run the risk that someone following the document will only include the three fields and configlet will not accept.

Granted, maybe that won't happen if they look at adjacent exercises and use them as examples, but even in that case it's still not clear the meaning of the UUID or how to get one.

**Comment by kytrinyx** [comment]
I think the two best options here are to either:

* include all the keys directly in the file, or
* link to https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md

Including the keys means that if (when?) we ever change it again, then we will have to update it here too, but it might be easier for someone to follow.

Linking might be fine, though, especially since as you mention people can look at the adjacent exercises.

**Comment by petertseng** [comment]
> if (when?) we ever change it again, then we will have to update it here too

And a more unfortunate thing is that every individual track README would want to get updated too. (This statement applies to anything that we inline into track READMEs instead of incorporate by reference).

I do wonder whether someone will ever wonder "why are so many things linked instead of just being in this file directly", but I haven't heard anyone give specific feedback complaining about that. We do have the benefit of having examples of other exercises in config.json. Exception is when the track is just getting started, so as long as docs are provided to the first maintainer things should be good.
